language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx

script:
  - make
  - make test
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode12.2
    - os: windows
    language: c
compiler: gcc

script:
  - gcc -o giftcardreader.c
  - ./my_program
